import { ionAddOutline, ionArrowBack, ionArrowForward, ionBarcodeOutline, ionCalendarOutline, ionCardOutline, ionCarOutline, ionCashOutline, ionChevronBackOutline, ionChevronDown, ionChevronForwardOutline, ionCreateOutline, ionFastFoodOutline, ionPencilOutline, ionPeopleOutline, ionPersonOutline, ionPricetagOutline, ionSettings, ionSettingsOutline, ionSparklesOutline, ionSwapHorizontalOutline, ionTrashOutline } from "@ng-icons/ionicons";
import { lucideDollarSign, lucideLayoutDashboard, lucideLayoutPanelLeft, lucideLogOut, lucidePencil } from "@ng-icons/lucide";

export const iconsConfig = {
    ionSettings, 
    ionSettingsOutline,
    ionAddOutline, 
    ionPencilOutline,
    ionCreateOutline,
    lucidePencil,
    ionSwapHorizontalOutline, 
    lucideLogOut, 
    lucideLayoutPanelLeft,
    lucideLayoutDashboard,
    lucideDollarSign,
    ionArrowBack,
    ionArrowForward,
    ionChevronBackOutline,
    ionChevronForwardOutline,
    ionChevronDown,
    ionFastFoodOutline,
    ionPricetagOutline,
    ionCardOutline,
    ionCarOutline,
    ionBarcodeOutline,
    ionCashOutline,
    ionCalendarOutline,
    ionTrashOutline,
    ionPersonOutline,
    ionSparklesOutline,
}